exports.compositoresListPage = function(compositores, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Compositores Management</title>
        </head>
        <body>
            <div class="w3-card-4">

                <header class="w3-container w3-teal">
                    <h1>Compositores 
                    <a class="w3-btn w3-round w3-grey" href="/compositores/registo">+</a>
                    </h1>
                    
                </header>
        
                <div class="w3-container">
                    <table class="w3-table-all">
                        <tr>
                            <th>Id</th><th>Name</th>
                            <th>Actions</th>
                        </tr>
                `

    for(let i=0; i < compositores.length ; i++){
        pagHTML += `
                <tr>
                    <td>${compositores[i].id}</td>
                    <td>
                        <a href="/compositores/${compositores[i].id}">
                            ${compositores[i].nome}
                        </a>
                    </td>
                    <td>
                        [<a href="/compositores/edit/${compositores[i].id}">Edit</a>]
                        [<a href="/compositores/delete/${compositores[i].id}">Delete</a>]
                    </td>
                </tr>
        `
    }

    pagHTML += `
            </table>
            </div>
                <footer class="w3-container w3-blue">
                    <h5>Generated by Tiago Rodrigues in ${d}</h5>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}


exports.compositorFormPage = function(d){
    return `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Compositores Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Compositor Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id"/>
                        <label>Nome</label>
                        <input class="w3-input w3-round" type="text" name="nome"/>
                        <label>Biografia</label>
                        <input class="w3-input w3-round" type="text" name="bio"/>
                        <label>Data Nascimento</label>
                        <input class="w3-input w3-round" type="text" name="dataNasc"/>
                        <label>Data Obito</label>
                        <input class="w3-input w3-round" type="text" name="dataObito"/>
                        <label>Periodo</label>
                        <input class="w3-input w3-round" type="text" name="periodo"/>
                    </fieldset>
                   
                    <button class="w3-btn w3-purple w3-mb-2" type="submit">Registar</button>
                </form>
                <footer class="w3-container w3-purple">
                    <h5>Generated by Tiago Rodrigues in ${d} - [<a href="/compositores">Voltar</a>]</h5>
                </footer>
            
            </div>
    `
}

exports.compositorFormEditPage = function(a, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Compositor Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Compositor Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                <fieldset>
                    <legend>Metadata</legend>
                    <label>Id</label>
                    <input class="w3-input w3-round" type="text" name="id" readonly value="${a.id}"/>
                    <label>Nome</label>
                    <input class="w3-input w3-round" type="text" name="nome" value="${a.nome}"/>
                    <label>Bio</label>
                    <input class="w3-input w3-round" type="text" name="gitlink" value="${a.bio}"/>
                    <label>Data Nascimento</label>
                    <input class="w3-input w3-round" type="text" name="dataNasc" value="${a.dataNasc}"/>
                    <label>Data Obito</label>
                    <input class="w3-input w3-round" type="text" name="dataObito"value="${a.dataObito}"/>
                    <label>Periodo</label>
                    <input class="w3-input w3-round" type="text" name="periodo"value="${a.periodo}"/>
                </fieldset>
                <button class="w3-btn w3-purple w3-mb-2" type="submit">Registar</button>
            </form>
                <footer class="w3-container w3-purple">
                    <h5>Generated by Tiago Rodrigues in ${d} - [<a href="/compositores">Voltar</a>]</h5>
                </footer>
            
            </div>
    `
    return pagHTML
}

exports.compositorPage = function(compositor, d ){
    var pagHTML = `
    <html>
    <head>
        <title>Compositor: ${compositor.id}</title>
        <meta charset="utf-8"/>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-teal">
                <h1>Compositor ${compositor.id}</h1>
            </header>

            <div class="w3-container">
                <ul class="w3-ul w3-card-4" style="width:50%">
                    <li><b>Nome: </b> ${compositor.nome}</li>
                    <li><b>ID: </b> ${compositor.id}</li>
                </ul>
            </div>
            <footer class="w3-container w3-teal">
                <address>Generated by Tiago Rodrigues in ${d} - [<a href="/compositores">Voltar</a>]</address>
            </footer>
        </div>
    </body>
    </html>
    `
    return pagHTML
}



// ***************************** PERIODOS ****************************************************
exports.periodosListPage = function(periodos, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Periodos Management</title>
        </head>
        <body>
            <div class="w3-card-4">

                <header class="w3-container w3-teal">
                    <h1>Periodos 
                    <a class="w3-btn w3-round w3-grey" href="/periodos/registo">+</a>
                    </h1>
                    
                </header>
        
                <div class="w3-container">
                    <table class="w3-table-all">
                        <tr>
                            <th>Id</th><th>Name</th>
                            <th>Actions</th>
                        </tr>
                `

    for(let i=0; i < periodos.length ; i++){
        pagHTML += `
                <tr>
                    <td>${periodos[i].id}</td>
                    <td>
                        <a href="/periodos/${periodos[i].id}">
                            ${periodos[i].nome}
                        </a>
                    </td>
                    <td>
                        [<a href="/periodos/edit/${periodos[i].id}">Edit</a>]
                        [<a href="/periodos/delete/${periodos[i].id}">Delete</a>]
                    </td>
                </tr>
        `
    }

    pagHTML += `
            </table>
            </div>
                <footer class="w3-container w3-blue">
                    <h5>Generated by Tiago Rodrigues in ${d}</h5>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}

exports.periodoFormPage = function(d){
    return `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Periodos Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Compositor Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id"/>
                        <label>Nome</label>
                        <input class="w3-input w3-round" type="text" name="nome"/>
                    </fieldset>
                   
                    <button class="w3-btn w3-purple w3-mb-2" type="submit">Registar</button>
                </form>
                <footer class="w3-container w3-purple">
                    <h5>Generated by Tiago Rodrigues in ${d} - [<a href="/periodos">Voltar</a>]</h5>
                </footer>
            
            </div>
    `
}

exports.periodoFormEditPage = function(a, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Periodo Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Periodo Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id" readonly value="${a.id}"/>
                        <label>Nome</label>
                        <input class="w3-input w3-round" type="text" name="nome" value="${a.nome}""/>
                    </fieldset>

                    <button class="w3-btn w3-purple w3-mb-2" type="submit">Register</button>
                </form>

                <footer class="w3-container w3-purple">
                    <h5>Generated by Tiago Rodrigues in ${d} - [<a href="/periodos">Voltar</a>]</h5>
                </footer>
            
            </div>
    `
    return pagHTML
}

exports.periodoPage = function(periodo, d ){
    var pagHTML = `
    <html>
    <head>
        <title>Periodo: ${periodo.id}</title>
        <meta charset="utf-8"/>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-teal">
                <h1>Periodo ${periodo.id}</h1>
            </header>

            <div class="w3-container">
                <ul class="w3-ul w3-card-4" style="width:50%">
                    <li><b>Nome: </b> ${periodo.nome}</li>
                    <li><b>ID: </b> ${periodo.id}</li>
                </ul>
            </div>
            <footer class="w3-container w3-teal">
                <address>Generated by Tiago Rodrigues in ${d} - [<a href="/periodos">Voltar</a>]</address>
            </footer>
        </div>
    </body>
    </html>
    `
    return pagHTML
}




exports.errorPage = function(errorMessage, d){
    return `
    <p>${d}: Error: ${errorMessage}</p>
    `
}